### ISSUE TITLE
Negative temperatures

### ISSUE THREAD

**Issue by danielfaust** [winlinvip/SimpleDHT#14]
Have you tested this library with negative temperatures?

With a DHT22 I'm getting values like -3276.3°C for values slightly below 0°C (possibly for -0.7°C).

-3277.0°C is not reached, that one is then 0.0°C

**Comment by winlinvip** [comment]
Nop, I didn't test it. I'll try it in our refrigerator.

**Comment by danielfaust** [comment]
Here is the code I'm using to work around this issue.

As I'm sending the data over BLE to an Android phone and the USB port of the ESP32 NodeMCU broke off (I'm using the library with that), making an on-device correction somewhat more laborious, i fixed it in the app which receives the data.

Before sending it to the phone I multiply with 100 and then cast to int, that makes the BLE decoding somewhat easier.

In the app I'm using the following to correct the issue:

```
int iTemp = characteristic.getIntValue(BluetoothGattCharacteristic.FORMAT_SINT32, 4);
if (iTemp < 0) {
    iTemp = -iTemp - 327700;
}
float fTemp = iTemp / 100.0;
```

**Comment by sulicz** [comment]
Hi, solution si:
```
    if (ptemperature) {
        if ( (temperature & 0x8000 )) {
          *ptemperature = (float) (temperature & 0x7FFF)/ -10.0;
        } else {
          *ptemperature = (float) temperature / 10.0;
        }
    }
```
in function SimpleDHT22::read2  and I changed all datatype short to uint16_t but datatype is may not a reason of problem.

**Comment by winlinvip** [comment]
Could u please file a PullRequest?

**Comment by danielfaust** [comment]
I will look into it

**Comment by danielfaust** [comment]
BTW, using a compressed gas duster (holding it upside down) can give you temps below the freezing point very quickly, then you can heat it up again with the fingers.

**Comment by winlinvip** [comment]
Merged

**Comment by winlinvip** [comment]
Please fix it for DHT11.

**Comment by danielfaust** [comment]
I don't have a DHT11 to test with. But since the DHT11 only works with temperatures equal to or above 0 °C, I think that sign flag never gets set. I preferred not to touch that code.

> [Good for 0-50°C temperature readings ±2°C accuracy](https://www.adafruit.com/product/386)

**Comment by winlinvip** [comment]
👌

**Comment by mapmelad** [comment]
Unfortunately still not displayed correctly :/ 

https://puu.sh/z23v3/7b8f96b37f.jpg

**Comment by danielfaust** [comment]
@mapmelad on what device are you running it? For me this works on an ESP32, maybe this is device dependent? When you use a previous commit, what does it show?

**Comment by mapmelad** [comment]
First, I obtained the values of the similarity -3277.0°C. 
I used the fix:
```
if (ptemperature) {
        if ( (temperature & 0x8000 )) {
          *ptemperature = (float) (temperature & 0x7FFF)/ -10.0;
        } else {
          *ptemperature = (float) temperature / 10.0;
        }
    }
```
Then, after the fix I started getting the values 255, 254 and so on
If I delete in the code the minus sign `*ptemperature = (float) (temperature & 0x7FFF)/ 10.0;` , it displays the temperature correctly, but there is no minus sign in the output.

**Comment by danielfaust** [comment]
Maybe this is due to the ArduinoBT -- which you're apparently using, judging from the screenshot -- being an 8 bit mcu while the ESP32 has a 32 bit cpu.

**Comment by winlinvip** [comment]
Should we reopen this issue? @danielfaust

**Comment by winlinvip** [comment]
Please test 1.0.9

**Comment by winlinvip** [comment]
![image](https://user-images.githubusercontent.com/2777660/44304529-a134a480-a390-11e8-947b-3f48432be971.png)

I put DHT11 into refrigerator, its data is:

```
Sample DHT11 with RAW bits...
Sample RAW Bits: 0010 1100 0000 0000 0000 0001 0000 0000 0010 1101 
Sample OK: 1 *C, 44 H
```

Always above 0C.

**Comment by winlinvip** [comment]
For DHT22: 

```
Sample DHT22 with RAW bits...
Sample RAW Bits: 0000 0011 1110 0111 1000 0000 0101 1010 1100 0100 
Sample OK: -9.00 *C, 99.90 RH%
```

```
Sample DHT22 with RAW bits...
Sample RAW Bits: 0000 0010 1101 1101 1000 0000 1000 1000 1110 0111 
Sample OK: -13.60 *C, 73.30 RH%
```


![image](https://user-images.githubusercontent.com/2777660/44304583-66cc0700-a392-11e8-9200-59c1a8ee359b.png)
