### ISSUE TITLE
Reading errors

### ISSUE THREAD

**Issue by tomiisp** [winlinvip/SimpleDHT#15]
DHT22 with ESP8266 producing in my case a lot of repeating read errors (sample rate 5sec), error rate was about 9:1 (error:success). Little looking in code and here seems was that issue:

```
int SimpleDHT::confirm(int pin, int us, byte level) {
...  
      delayMicroseconds(10);
...
}
```

changing delayMicroseconds(10); to delayMicroseconds(20); fix this problem, 0 errors after 2hours of testing

**Comment by winlinvip** [comment]
It may fix the problem, but I think it's not the right answer. I think we must find out why delay(10us) caused the error, right?

**Comment by vitamins** [comment]
I tried to apply this and it didn't help, the number of errors increased.
The adafruit library is working fine for me.
https://github.com/adafruit/DHT-sensor-library

**Comment by winlinvip** [comment]
I think the confirm function, which split us to pieces of 10us, causes deviation.

**Comment by glewellyn** [comment]
Again, no root cause, but increasing the delayMicroseconds to 20 did solve my problem as well.

**Comment by winlinvip** [comment]
Please test 1.0.9
