### ISSUE TITLE
diff values for Humidity for dht11&dht22

### ISSUE THREAD

**Issue by enginm** [winlinvip/SimpleDHT#17]
Hi,
thanks for library,

i have an issue that i don't understand,

i am reading different Humidity values on same breadboard with diff sensor,

here is the result:
Sample RAW Bits: 0100 0011 0000 0000 0001 0101 0000 0000 0101 1000 
Sample OK for DHT11: 21 *C, 67 %
Sample RAW Bits: 0000 0001 1110 1011 0000 0000 1100 1001 1011 0101 
Sample OK for DHT22: 20 *C, 49 %

**Comment by Rayzor53** [comment]
As I understand it, the DHT11 gives its measurements as absolute humidity,
and the DHT22 gives relative humidty, which is affected by temperature.

**Comment by DaleSchultz** [comment]
well, I was reading the lines in SimpleDHT.h and its states:

    //      For DHT11, in H, such as 35H.
    //      For DHT22, in RH%, such as 53%RH.

However, the data sheet states it returns **Relative Humidity.**
See https://www.electronicoscaldas.com/datasheet/DHT11_Aosong.pdf

I get a value of 35 right now at 23°C - and if that was absolute humidity the RH% would be well over 100%

So this means the original posters question is unresolved, and I want to suggest that the .h file get updated as a simple documentation issue.

**Comment by winlinvip** [comment]
Patch welcome.
