### ISSUE TITLE
Support DHT22 sensor.

### ISSUE THREAD

**Issue by mbeacom** [winlinvip/SimpleDHT#2]
@winlinvip Do you anticipate extending this to support the DHT22 model?

**Comment by winlinvip** [comment]
@mbeacom No plan, I have no time to play, 😄 
BTW: Seems there are lots of libraries about the DHT22, why not use them?

**Comment by mbeacom** [comment]
Honestly, I was just excited to see your DHT11 package, since I've been following you on GH as of lately and I'm in the middle of working on a personal, side project using the DHT11 and 22s. Haha

Regardless,  Thanks for everything @winlinvip !

**Comment by winlinvip** [comment]
So you are using Arduino to Sample the temperature and humidity by DHT11/22?

**Comment by mbeacom** [comment]
👍 Ongoing sampling with a raspberry pi and Arduino to monitor temperature/RH!

**Comment by winlinvip** [comment]
It works~ I have done that.
BTW: It's not possible for raspberry-pi to directly drive the DHT11(maybe use C is ok, but python is not), for the DHT11 use Nms interval as the protocol, while the Arduino is good to do such things.

You can use Serial for Raspberrypi to communicate with Arduino. https://github.com/winlinvip/SimpleSerial
Use Arduino to sample the DHT11 and send the data to RaspeberryPi by usb serial port.

**Comment by winlinvip** [comment]
It seems the protocol between DHT22 and DHT11 is not very different, I can support DHT22, but I haven't get a DHT22, can you test it for me?

The major difference of DHT22 and DHT11 is the startup signal, DHT11 PULL LOW 18ms+, while DHT22 PULL LOW 500us+ or 1ms+.

**Comment by winlinvip** [comment]
I have supported DHT22 in https://github.com/winlinvip/SimpleDHT/commit/32bf0286397590c57ff4b3f428aa2c0cc1a496ef, however I didn't test it yet, please use [example](https://github.com/winlinvip/SimpleDHT/blob/master/examples/DHT22Default/DHT22Default.ino) to test it. Other examples should also work by changing the class SimpleDHT11 to SimpleDHT22.

After testing it, please close this issue. Thanks~

**Comment by mbeacom** [comment]
@winlinvip I will test the patch sometime this evening and let you know!

**Comment by winlinvip** [comment]
Great, what's the result?

**Comment by equake** [comment]
I'm trying to use this lib with an DHT22 without success. I get error 101 / 102 while trying to fetch temperature.

I can make some tests if you want!

**Comment by winlinvip** [comment]
@equake Please do some tests.

**Comment by winlinvip** [comment]
![image](https://user-images.githubusercontent.com/2777660/27774370-9b41f792-5fc3-11e7-845b-a5e3ebbc5801.png)

I will refine the protocol according to http://akizukidenshi.com/download/ds/aosong/AM2302.pdf

**Comment by winlinvip** [comment]
I have verify the v1.0.5, it works with DHT11:
```
Sample DHT11 with RAW bits...
Sample RAW Bits: 0001 1110 0000 0000 0001 1100 0000 0000 0011 1010 
Sample OK: 28 *C, 30 H
=================================
Sample DHT11 with RAW bits...
Sample RAW Bits: 0001 1110 0000 0000 0001 1100 0000 0000 0011 1010 
Sample OK: 28 *C, 30 H
```

With DHT22:
```
Sample DHT22 with RAW bits...
Sample RAW Bits: 0000 0010 1011 0001 0000 0001 0001 1111 1101 0011 
Sample OK: 28.70 *C, 68.90 RH%
=================================
Sample DHT22 with RAW bits...
Sample RAW Bits: 0000 0010 1010 1000 0000 0001 0010 0000 1100 1011 
Sample OK: 28.80 *C, 68.00 RH%
```

> Remark: Notice that the DHT11 humidity is H, while DHT22 is RH%, for example:
```
Humidity：0011 0101=35H=53%RH
```

**Comment by Rayzor53** [comment]
Doesn't work below freezing. Returns an absurd answer -2856. This with DHT22.

**Comment by winlinvip** [comment]
@Rayzor53 Dup to #14
