### ISSUE TITLE
undeclared functions when compiling for non-AVR boards

### ISSUE THREAD

**Issue by christandlg** [winlinvip/SimpleDHT#24]
when compiling for ESP8266 or ESP32 (others propably too) compilation fails with the following error:

> C:\Users\user\Documents\Arduino\libraries\SimpleDHT\SimpleDHT.cpp:72:27: error: no 'int SimpleDHT::getBitmask()' member function declared in class 'SimpleDHT'
> 
>  int SimpleDHT::getBitmask() {
> 
>                            ^
> 
> C:\Users\user\Documents\Arduino\libraries\SimpleDHT\SimpleDHT.cpp:76:24: error: no 'int SimpleDHT::getPort()' member function declared in class 'SimpleDHT'
> 
>  int SimpleDHT::getPort() {
> 
>                         ^

this is because the function definitions of SimpleDHT::getBitmask() and SimpleDHT::getPort() are not enclosed within a conditional compilation block, unlike their declarations in SimpleDHT.h

**Comment by paulocotta** [comment]
I also had the same problem

int SimpleDHT::getBitmask() {
int SimpleDHT::getPort() {

**Comment by rolfbachmann** [comment]
Had the same problem too. Downgrade to 1.0.8 works for me.

**Comment by winlinvip** [comment]
@rolfbachmann Please test 1.0.12
