### ISSUE TITLE
Problems using Arduino Uno

### ISSUE THREAD

**Issue by micmader** [winlinvip/SimpleDHT#40]
I am using version 1.0.12 with Arduino Uno.
I used the Example DHT11 files and needed to change setup to:

`Serial.begin(9600);`

Because Arduino Only support this. Using higher values results in crap charachters displayed on serial display.
I obtain the following errors:

 
Sample DHT11...
Read DHT11 failed, err=4112
 
Sample DHT11...
Read DHT11 failed, err=3088
 
Sample DHT11...
Read DHT11 failed, err=4112
 
Sample DHT11...
Read DHT11 failed, err=3088
 

(removed the ===)

Is it possible that the sensor cannot be used on Arduino Uno?
Or is it broken?

**Comment by chiragchinvar** [comment]
Make sure you have selected the correct sensor type in your #define statement ie if you are using sensor type 22 it should be #define DHTTYPE DHT22.
