### ISSUE TITLE
DHT22 reading doesn't work when WiFi switched off

### ISSUE THREAD

**Issue by weinerg** [winlinvip/SimpleDHT#47]
Hi,
I changed from version 1.0.12 to 1.0.14 and now the reading of values from DHT22 doesn't work anymore, when Wifi is switchde off.

I use ESP8266.
```
SimpleDHT22 dht22(DHTPIN);
...
WiFi.mode( WIFI_OFF );
WiFi.forceSleepBegin();
delay( 1 );
...
err = SimpleDHTErrSuccess;
if ((err = dht22.read2(&temp, &hum, NULL)) != SimpleDHTErrSuccess)
{
```
Without the 2nd part all works fine also with v1.0.14, but when using the 2nd part, it only work with v1.0.12.

**Comment by winlinvip** [comment]
I have reverted the 1.0.14

**Comment by weinerg** [comment]
Actually the problem happens with any version greater than 1.0.12.
