### ISSUE TITLE
Library 1.0.14 Issue

### ISSUE THREAD

**Issue by Sinix10** [winlinvip/SimpleDHT#50]
I have come to report that, with this library version, I am getting more fail readings than successful ones.
It is not happening on the previous version "1.0.13", which works perfectly ATM.
Using ESP8266 + DHT22.

**Comment by winlinvip** [comment]
Seems the 1.0.13 is stable than 1.0.14

**Comment by winlinvip** [comment]
I revert the 1.0.14 https://github.com/winlinvip/SimpleDHT/commit/d06f831888f0bbdf23a2956cebd6dbbb49f2839f
