### ISSUE TITLE
doubt: what is 'raw bits' ?

### ISSUE THREAD

**Issue by denisdemaisbr** [winlinvip/SimpleDHT#6]
Hi! How use it ? What is it useful for?

NOTE:
library works with Arduino IDE v1.6.13

BN: Arduino/Genuino Uno
VID: 2341
PID: 0043
SN: 95530343335351

**Comment by winlinvip** [comment]
You can run the example https://github.com/winlinvip/SimpleDHT/blob/master/examples/DHT11Default/DHT11Default.ino
